apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: clusterpedia-system
type: Opaque
stringData:
  DATABASE_DSN: "kpanda:@tcp(10.6.216.81:32549)/kpanda?charset=utf8mb4&multiStatements=true&parseTime=true"