---
# Source: clusterpedia/templates/apiserver-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-clusterpedia-apiserver
  namespace: default
  labels:
    app.kubernetes.io/name: clusterpedia
    helm.sh/chart: clusterpedia-2.6.3
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "v0.9.0"
---
# Source: clusterpedia/templates/clustersynchro-manager-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-clusterpedia-clustersynchro-manager
  namespace: default
  labels:
    app.kubernetes.io/name: clusterpedia
    helm.sh/chart: clusterpedia-2.6.3
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "v0.9.0"
---
# Source: clusterpedia/templates/controller-manager-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-clusterpedia-controller-manager
  namespace: default
  labels:
    app.kubernetes.io/name: clusterpedia
    helm.sh/chart: clusterpedia-2.6.3
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "v0.9.0"
---
# Source: clusterpedia/templates/internalstorage-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-clusterpedia-internalstorage
  namespace: default
  labels:
    app.kubernetes.io/name: clusterpedia
    helm.sh/chart: clusterpedia-2.6.3
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "v0.9.0"
    app: test-clusterpedia-internalstorage
    internalstorage.clusterpedia.io/type: mysql
data:
  password:
---
# Source: clusterpedia/templates/internalstorage-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-clusterpedia-internalstorage
  namespace: default
  labels:
    app.kubernetes.io/name: clusterpedia
    helm.sh/chart: clusterpedia-2.6.3
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "v0.9.0"
data:
  internalstorage-config.yaml: |-
    type: "mysql"
    dsn: ""
    host: ""
    port: 
    user: 
    database: 
    
    connPool:
      maxIdleConns: 5
      maxOpenConns: 40
      connMaxLifetime: 60m
---
# Source: clusterpedia/templates/scripts-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-clusterpedia-scripts
  namespace: default
  labels:
    app.kubernetes.io/name: clusterpedia
    helm.sh/chart: clusterpedia-2.6.3
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "v0.9.0"
data:
  parse-yaml.sh: |
    function parse_yaml() {
      local prefix=$2
      local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
      sed -ne "s|^\($s\):|\1|" \
            -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
            -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
      awk -F$fs '{
          indent = length($1)/2;
          vname[indent] = $2;
          for (i in vname) {if (i > indent) {delete vname[i]}}
          if (length($3) > 0) {
            vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
            printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
          }
      }'
    }

    function parse_mysql_dsn() {
        local dsn=$1
        if [ -z $dsn ]
        then
            return
        fi

        IFS='?' read -r -a _dsn <<< $dsn; upnad=${_dsn[0]}
        IFS='/' read -a upnad <<< $upnad; upna=${upnad[0]}; database=${upnad[1]}
        IFS='(' read -a upna <<< $upna ; upn=${upna[0]}; address=${upna[1]%?}
        IFS='@' read -r -a upn <<< $upn; up=${upn[0]}; protocal=${upn[1]}
        IFS=':' read -r -a up <<< $up; user=${up[0]}; password=${up[1]}

        if [ ! -z $address ]
        then
            IFS=':' read -r -a address <<< $address; host=${address[0]}; port=${address[1]}
        fi

        echo "database=\"$database\""
        echo "host=\"$host\""
        echo "port=\"$port\""
        echo "user=\"$user\""
        echo "password=\"$password\""
    }
    
    function parse_postgres_dsn() {
        local dsn=$1
        if [ -z $dsn ]
        then
            return
        fi

        kvpairs=($dsn)
        for kv in "${kvpairs[@]}"; do
            if [[ $kv == "host"* ]]; then
            IFS='=' read -r -a _kv <<< $kv; host=${_kv[1]}
            fi
            if [[ $kv == "user"* ]]; then
            IFS='=' read -r -a _kv <<< $kv; user=${_kv[1]}
            fi
            if [[ $kv == "port"* ]]; then
            IFS='=' read -r -a _kv <<< $kv; port=${_kv[1]}
            fi
            if [[ $kv == "dbname"* ]]; then
            IFS='=' read -r -a _kv <<< $kv; database=${_kv[1]}
            fi
        done
    
        echo "database=\"$database\""
        echo "host=\"$host\""
        echo "port=\"$port\""
        echo "user=\"$user\""
    }

    function create_variables() {
        local yaml_file="$1"
        eval "$(parse_yaml "$yaml_file")"

        if [ -n "$DB_DSN" ]
        then
            dsn="$DB_DSN"
        fi

        if [ $type == "mysql" ]
        then
            eval $(parse_mysql_dsn "$dsn")
        fi
    
        if [ $type == "postgres" ]
        then
            eval $(parse_postgres_dsn "$dsn")
        fi
    }
---
# Source: clusterpedia/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-clusterpedia
  labels:
    app.kubernetes.io/name: clusterpedia
    helm.sh/chart: clusterpedia-2.6.3
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "v0.9.0"
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ["*"]
  - nonResourceURLs: ['*']
    verbs: ["get"]
---
# Source: clusterpedia/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-clusterpedia
  labels:
    app.kubernetes.io/name: clusterpedia
    helm.sh/chart: clusterpedia-2.6.3
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "v0.9.0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-clusterpedia
subjects:
  - kind: ServiceAccount
    name: test-clusterpedia-apiserver
    namespace: default
  - kind: ServiceAccount
    name: test-clusterpedia-clustersynchro-manager
    namespace: default
  - kind: ServiceAccount
    name: test-clusterpedia-controller-manager
    namespace: default
---
# Source: clusterpedia/templates/apiserver-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-clusterpedia-apiserver
  namespace: default
  labels:
    app.kubernetes.io/name: clusterpedia
    helm.sh/chart: clusterpedia-2.6.3
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "v0.9.0"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: test-clusterpedia-apiserver
---
# Source: clusterpedia/templates/clustersynchro-manager-metrics-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-clusterpedia-clustersynchro-manager-metrics
  namespace: default
  labels:
    app: test-clusterpedia-clustersynchro-manager
    app.kubernetes.io/name: clusterpedia
    helm.sh/chart: clusterpedia-2.6.3
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "v0.9.0"
spec:
  ports:
  - name: metrics
    port: 8081
    targetPort: 8081
  selector:
    app: test-clusterpedia-clustersynchro-manager
---
# Source: clusterpedia/templates/apiserver-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-clusterpedia-apiserver
  namespace: default
  labels:
    app.kubernetes.io/name: clusterpedia
    helm.sh/chart: clusterpedia-2.6.3
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "v0.9.0"
    app: test-clusterpedia-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: clusterpedia
      app.kubernetes.io/instance: test
      app: test-clusterpedia-apiserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clusterpedia
        helm.sh/chart: clusterpedia-2.6.3
        app.kubernetes.io/instance: test
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/version: "v0.9.0"
        app: test-clusterpedia-apiserver
    spec:
      
      initContainers:
      - name: check-storage
        image: docker.io/bitnamilegacy/mysql:8.0.40-debian-12-r5
        command: 
          - /bin/bash
          - -ec
          - |
            # Load YAML data into a Bash variable
            source /opt/scripts/parse-yaml.sh;
            create_variables /etc/clusterpedia/storage/internalstorage-config.yaml;
            if [ -z $password ]; then password=${DB_PASSWORD}; fi;
            until mysqladmin status -u${user} -p${password} --host=${host} --port=${port}; do
            echo waiting for database check && sleep 1; 
            done;
            echo 'DataBase OK ✓'
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: test-clusterpedia-internalstorage
                key: password
          - name: DB_DSN
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: DATABASE_DSN
        volumeMounts:
        - name: internalstorage-config
          mountPath: /etc/clusterpedia/storage
          readOnly: true
        - name: scripts
          mountPath: /opt/scripts
          readOnly: true
      containers:
      - name: test-clusterpedia-apiserver
        image: ghcr.io/clusterpedia-io/clusterpedia/apiserver:v0.9.0
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/bin/apiserver
        - --secure-port=443
        - --storage-config=/etc/clusterpedia/storage/internalstorage-config.yaml
        - -v=3
        env:
        - name: CLUSTERPEDIA_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-clusterpedia-internalstorage
              key: password
        - name: DB_DSN
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_DSN
        
        - name: GODEBUG
          value: netdns=go
        volumeMounts:
        - name: internalstorage-config
          mountPath: /etc/clusterpedia/storage
          readOnly: true
      serviceAccountName: test-clusterpedia-apiserver
      volumes:
        - name: internalstorage-config
          configMap:
            name: test-clusterpedia-internalstorage
        - name: scripts
          configMap:
            name: test-clusterpedia-scripts
---
# Source: clusterpedia/templates/clustersynchro-manager-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-clusterpedia-clustersynchro-manager
  namespace: default
  labels:
    app.kubernetes.io/name: clusterpedia
    helm.sh/chart: clusterpedia-2.6.3
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "v0.9.0"
    app: test-clusterpedia-clustersynchro-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: clusterpedia
      app.kubernetes.io/instance: test
      app: test-clusterpedia-clustersynchro-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clusterpedia
        helm.sh/chart: clusterpedia-2.6.3
        app.kubernetes.io/instance: test
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/version: "v0.9.0"
        app: test-clusterpedia-clustersynchro-manager
    spec:
      
      initContainers:
      - name: check-storage
        image: docker.io/bitnamilegacy/mysql:8.0.40-debian-12-r5
        command: 
          - /bin/bash
          - -ec
          - |
            # Load YAML data into a Bash variable
            source /opt/scripts/parse-yaml.sh;
            create_variables /etc/clusterpedia/storage/internalstorage-config.yaml;
            if [ -z $password ]; then password=${DB_PASSWORD}; fi;
            until mysqladmin status -u${user} -p${password} --host=${host} --port=${port}; do
            echo waiting for database check && sleep 1; 
            done;
            echo 'DataBase OK ✓'
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: test-clusterpedia-internalstorage
                key: password
          - name: DB_DSN
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: DATABASE_DSN
        volumeMounts:
        - name: internalstorage-config
          mountPath: /etc/clusterpedia/storage
          readOnly: true
        - name: scripts
          mountPath: /opt/scripts
          readOnly: true
      containers:
      - name: test-clusterpedia-clustersynchro-manager
        image: ghcr.io/clusterpedia-io/clusterpedia/clustersynchro-manager:v0.9.0
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/bin/clustersynchro-manager
        - --storage-config=/etc/clusterpedia/storage/internalstorage-config.yaml
        - --leader-elect-resource-namespace=default
        - --leader-elect-lease-duration=15s
        - --leader-elect-renew-deadline=10s
        - --leader-elect-retry-period=2s
        - --leader-elect-resource-lock=leases
        - --worker-number=5
        env:
          - name: CLUSTERPEDIA_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: test-clusterpedia-internalstorage
                key: password
          - name: DB_DSN
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: DATABASE_DSN
          - name: GODEBUG
            value: netdns=go
        volumeMounts:
          - name: internalstorage-config
            mountPath: /etc/clusterpedia/storage
            readOnly: true
      serviceAccountName: test-clusterpedia-clustersynchro-manager
      volumes:
        - name: internalstorage-config
          configMap:
            name: test-clusterpedia-internalstorage
        - name: scripts
          configMap:
            name: test-clusterpedia-scripts
---
# Source: clusterpedia/templates/controller-manager-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-clusterpedia-controller-manager
  namespace: default
  labels:
    app.kubernetes.io/name: clusterpedia
    helm.sh/chart: clusterpedia-2.6.3
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "v0.9.0"
    app: test-clusterpedia-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: clusterpedia
      app.kubernetes.io/instance: test
      app: test-clusterpedia-controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clusterpedia
        helm.sh/chart: clusterpedia-2.6.3
        app.kubernetes.io/instance: test
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/version: "v0.9.0"
        app: test-clusterpedia-controller-manager
    spec:
      
      containers:
      - name: test-clusterpedia-controller-manager
        image: ghcr.io/clusterpedia-io/clusterpedia/controller-manager:v0.9.0
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/bin/controller-manager
        - --leader-elect-resource-namespace=default
      serviceAccountName: test-clusterpedia-controller-manager
---
# Source: clusterpedia/templates/apiserver-apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.clusterpedia.io
  labels:
    app.kubernetes.io/name: clusterpedia
    helm.sh/chart: clusterpedia-2.6.3
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "v0.9.0"
spec:
  insecureSkipTLSVerify: true
  group: clusterpedia.io
  groupPriorityMinimum: 1000
  versionPriority: 100
  service:
    name: test-clusterpedia-apiserver
    namespace: default
  version: v1beta1
