storageInstallMode: external

mysql:
  enabled: false

postgresql:
  enabled: false

externalStorage:
  type: mysql
  createDatabase: false
  dsn:
    secretKeyRef:
      name: database-credentials
      key: DATABASE_DSN

persistenceMatchNode: None